### ISSUE TITLE
Little and basic question

### ISSUE THREAD

**Issue by pendex900x** [Kshitijpawar/License_Plate_Detection#1]
On the file "License_Plate_Detection.ipynb" in the part of "Downloading the model"

What should i put in the MODEL part?

Here:

`MODEL_FILE = MODEL + '.tar.gz'`

Which model for example?

thanks!

**Comment by Kshitijpawar** [comment]
MODELS_CONFIG = {
    'ssd_mobilenet_v2': {
        'model_name': 'ssd_mobilenet_v2_coco_2018_03_29',
        'pipeline_file': 'ssd_mobilenet_v2_coco.config',
        'batch_size': 12
    },
    'faster_rcnn_inception_v2': {
        'model_name': 'faster_rcnn_inception_v2_coco_2018_01_28',
        'pipeline_file': 'faster_rcnn_inception_v2_pets.config',
        'batch_size': 12
    },
    'rfcn_resnet101': {
        'model_name': 'rfcn_resnet101_coco_2018_01_28',
        'pipeline_file': 'rfcn_resnet101_pets.config',
        'batch_size': 8
    }
}

You have options to choose different pre-trained models
1.)ssd_mobilenet_v2 (Used in this notebook)
2.)faster_rcnn_inception_v2
3.)rfcn_resnet101

If you want to use another model just change the contents in the variable 'selected_model'

**Comment by pendex900x** [comment]
Thanks for your answer!
